### ISSUE TITLE
last 02

### ISSUE THREAD

**Issue by pilkasnamas** [test-pilkas01/webhook-A#12]
[Task](http://localhost:9000/project/557957aa8a14955d14268cb6/issue/55799411c21a6aa115a6bf49) with ***Low*** priority was created by ***vidmantas@trackduck.com***:

```
last 01
```

[![Issue screenshot](https://devtrackduck.s3.amazonaws.com/crop/557957aa8a14955d14268cb6-1434031120739-117-176)](http://localhost:9000/preview/awsi/557957aa8a14955d14268cb6-1434031120739-117-176)

Environment: ***Chrome 43*** on ***Mac OS*** with ***1440x805*** screen size.

Check it in your [website](http://localhost:9000/mockups/557957aa8a14955d14268cb6/557957c48a14955d14268cb9/557957c48a14955d14268cba/?tdtask=55799411c21a6aa115a6bf49) or get [more details...](http://localhost:9000/project/557957aa8a14955d14268cb6/issue/55799411c21a6aa115a6bf49)

**Comment by pilkasnamas** [comment]
me like it

**Comment by pilkasnamas** [comment]
go A

**Comment by pilkasnamas** [comment]
go B

**Comment by pilkasnamas** [comment]
go C

**Comment by pilkasnamas** [comment]
go close

**Comment by vidmantasmln** [comment]
good to go
